### ISSUE TITLE
Advertising package

### ISSUE THREAD

**Issue by traverseda** [zacanger/styled-reset#13]
It looks like this project depends on https://github.com/feross/funding, a project intended to show advertising in a projects build log.

I'm not familiar with your project, I'm just looking through a list of projects that depend on `feross/funding`. It's my understanding that right now there aren't any advertising messages actually showing, but if you're uncomfortable with the possibility of advertisements in build logs that's something you might want to look into.

**Comment by zautumnz** [comment]
Thanks for the heads up. It looks like that package is a transitive dep of `standard`, which is only a dev dependency, so shouldn't affect any users, only folks who might need to submit changes. I'm fine with leaving it how it is for now.
