### ISSUE TITLE
Uses of opencollective

### ISSUE THREAD

**Issue by DavidHenri008** [zacanger/styled-reset#14]
# Is this a feature request or a bug?
This is an issue.

# Expected behavior:
The library uses the old opencollective package. This package does not seem to be maintained anymore and it relies on an old babel-polyfill package. This is causing warnings.

# Actual behavior:
It would be nice to use a different package that uses up-to-date dependencies.

# Environment info (relevant browser, OS, etc.; run `npx envinfo`):
System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
    Memory: 17.37 GB / 31.88 GB
  Binaries:
    Node: 12.11.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.1 - C:\Users\ABC\AppData\Roaming\npm\yarn.CMD
    npm: 6.12.1 - C:\Program Files\nodejs\npm.CMD
  Utilities:
    Git: 2.23.0. - C:\Program Files\Git\cmd\git.EXE
  IDEs:
    VSCode: 1.40.2 - C:\Users\ABC\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  Browsers:
    Edge: 44.18362.449.0
    Internet Explorer: 11.0.18362.1

**Comment by zautumnz** [comment]
Thanks! Now that `npm fund` is a thing, I'll remove the opencollective dependencies.

**Comment by zautumnz** [comment]
Fixed in v4.0.8.
