### ISSUE TITLE
Please stop releasing versions when updating devDependencies

### ISSUE THREAD

**Issue by MeLlamoPablo** [zacanger/styled-reset#18]
Hello!

I've noticed many repos releasing versions when updating parts of the code that don't affect end users, like documentation or devDependencies.

I understand that updating a devDependency related to the build process might warrant a new version since the build output might have changed, but for example in the case of 8412b29 nothing like that was updated. So updating to v4.3.4 brings no value at all to the users of this package.

I appreciate all the effort put into this package! This is just a minor inconvenience, but it happens frequently here and in other packages so I thought I'd bring it up.

At our company, we manually review all changelogs as part of our dependency update process. We see many changelogs entries consisting of "update docs" which waste our time. One is not a big deal, but over time it adds up.

So please consider not publishing versions for these kind of changes. Thanks for your time! :slightly_smiling_face:

**Comment by zautumnz** [comment]
Fair point, I habitually `npm version` after doing even non-code changes, but there's no actual reason to do so if there was no change to the build output. I'll be careful of that in the future. :)
