### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by rodperottoni** [zacanger/styled-reset#19]
This is a rather unusual request, but I was wondering if there's any chances you could change the licensing of this package to something more open-source friendly (MIT perhaps)? I'm currently on discussions with lawyers who seem to be worried about LGPL usage in the project I am currently working on and despite my best efforts it seems like a more permissive license would just make the whole process much smoother.

**Comment by pstoica** [comment]
Same, I'm having to remove this library from our project.

**Comment by zautumnz** [comment]
Yes. See version 4.4.0.
